version: '2'
services:
  couchdb:
    image: docker.io/bitnami/couchdb:3-debian-10
    environment:
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
    volumes:
      - couchdb_data:/bitnami/couchdb
volumes:
  couchdb_data:
    driver: local
